title: 'alicjaszabelska.github.io'
name: 'Alicja Szabelska-Beręsewicz'
email: alicja.szabelska@up.poznan.pl
permalink: /aktualnosci/:year/:month/:day/:title/

menus:
  main:
    - title: 'home'
      href: '/'
    - title: 'Aktualności'
      href: '/aktualnosci/'
    - title: 'CV'
      href: '/cv/'
    - title: 'Dydaktyka'
      href: '/dydaktyka/'
    - title: 'Kontakt'
      href: '/kontakt/'
    
